title: Ken Harris
url: https://kenhv.com
permalink: /blog/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true

destination: public
highlighter: none
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-og-image
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-toc

# SEO
description: Tech enthusiast. Occasional doer of stuff. @KenHV
author:
  name: Ken Harris
  twitter: KensurHV
  url: https://kenhv.com
twitter:
  username: KensurHV
  card: summary_large_image
social:
  name: Ken Harris
  links:
    - https://twitter.com/KensurHV
    - https://github.com/KenHV
    - https://t.me/KenHV

# OG Image
og_image:
  domain: "kenhv.com"
  canvas:
    background_color: "#ffffff"
  header:
    font_family: "Inter, Bold"
    color: "#121212"
  content:
    font_family: "Inter, Bold"
    color: "#121212"
  image: /assets/images/og-logo.jpg

# Target Blank
target-blank:
  noreferrer: false
