title = "Ken Harris"
author = "Ken Harris"
base_url = "https://kenhv.com"

external_links_target_blank = true
compile_sass = true
generate_feed = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[slugify]
paths = "safe"

[extra]
twitter_username = "@KensurHV"
