base_url = "https://kenhv.com"
title = "Ken Harris"
description = "Tech enthusiast. Occasional doer of stuff. @KenHV"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "feed.xml"
# taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
# taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Ken Harris"
id = "KenHV"
bio = ""
avatar = "/img/avatar.webp"
links = [
    { name = "GitHub", icon = "github", url = "https://github.com/KenHV" },
    { name = "Email", icon = "email", url = "mailto:ken@kenhv.com" },
    { name = "Telegram", icon = "telegram", url = "https://t.me/KenHV" },
]
banner = "/img/banner.webp"     # 1200x630 image for OpenGraph

homepage_layout = "about"             # "about" | "list" | "recent"

recent_max = 15
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "Blog", path = "/blog", is_external = false },
    #{ name = "GitHub", path = "https://github.com/KenHV", is_external = true },
    #{ name = "Mail", path = "mailto:ken@kenhv.com", is_external = true },
    #{ name = "Telegram", path = "https://t.me/KenHV", is_external = true },

    # { name = "projects", path = "/projects", is_external = false },
    # { name = "about", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true                     # Whether to display your id on homepage
blog_categorized = false               # Whether to categorize blog posts
blur_effect = false                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = false                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2024 KenHV"
footer_credits = false                 # Whether to show "powered by zola and serene" in footer

not_found_error = "404 - Page Not Found"
not_found_recover_text = "« Home »"
